Issue {issueClosedAt = Just (GithubDate {fromGithubDate = 2016-02-03 13:53:00 UTC}), issueUpdatedAt = GithubDate {fromGithubDate = 2016-02-03 13:56:16 UTC}, issueEventsUrl = "https://api.github.com/repos/lamby/django-slack/issues/28/events", issueHtmlUrl = Just "https://github.com/lamby/django-slack/issues/28", issueClosedBy = Nothing, issueLabels = [], issueNumber = 28, issueAssignee = Nothing, issueUser = GithubUser {githubOwnerAvatarUrl = "https://avatars.githubusercontent.com/u/6982419?v=3", githubOwnerLogin = "nedjam", githubOwnerUrl = "https://api.github.com/users/nedjam", githubOwnerId = 6982419, githubOwnerGravatarId = Just ""}, issueTitle = "Indentation error in 4.2.4", issuePullRequest = Nothing, issueUrl = "https://api.github.com/repos/lamby/django-slack/issues/28", issueCreatedAt = GithubDate {fromGithubDate = 2016-02-03 13:46:07 UTC}, issueBody = Just "There seems to have been an indentation error introduced in the latest release an hour ago. See below:\r\n\r\n```\r\n  File \"/usr/local/lib/python2.7/site-packages/django_slack/api.py\", line 86\r\n    \"URL is not specified\"\r\n    ^\r\nIndentationError: unexpected indent\r\n```\r\n\r\n", issueState = "closed", issueId = 131030848, issueComments = 3, issueMilestone = Nothing}