IssueComment {issueCommentUpdatedAt = GithubDate {fromGithubDate = 2015-10-13 08:13:59 UTC}, issueCommentUser = GithubUser {githubOwnerAvatarUrl = "https://avatars.githubusercontent.com/u/17590?v=3", githubOwnerLogin = "bastianh", githubOwnerUrl = "https://api.github.com/users/bastianh", githubOwnerId = 17590, githubOwnerGravatarId = Just ""}, issueCommentUrl = "https://api.github.com/repos/lamby/django-slack/issues/comments/147642067", issueCommentCreatedAt = GithubDate {fromGithubDate = 2015-10-13 08:13:59 UTC}, issueCommentBody = "ok .. my fault. When I added your library that was the first error I got .. and since it's the same error message that I got from other libraries I thought it had to do with django 1.9 \r\n\r\nI fixed it by uncommenting the import in __init__.py and then I stumbled over the missing python3 compatiblity in backend.py so I fixed that.\r\n \r\nThe problem is that your way of importing the backend silenty ignores the import error that are caused by the missing python 3 compatiblity in the backends.py file but then later causes django to fail to start.", issueCommentId = 147642067}